
import React from 'react';
import { SaleRecord } from '../types';

interface Props {
  sale: SaleRecord;
}

const Receipt: React.FC<Props> = ({ sale }) => {
  return (
    <div className="bg-white text-slate-900 font-mono text-sm max-w-sm mx-auto">
      <div className="text-center mb-10 border-b border-slate-100 pb-10">
        <h2 className="text-3xl font-black uppercase tracking-tighter mb-2">ShopMaster Pro</h2>
        <p className="text-[10px] text-slate-400 font-bold">CERTIFIED MERCHANT: Terminal-A01</p>
        <p className="text-[10px] text-slate-400 font-bold uppercase mt-1 tracking-widest">Tax Registration: TR-19283746</p>
      </div>

      <div className="bg-slate-50 p-6 rounded-3xl mb-8 space-y-3 border border-slate-100">
        <div className="flex justify-between items-center border-b border-slate-200 pb-2 mb-2">
           <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Customer ID</span>
           <span className="text-[10px] font-black bg-white px-3 py-1 rounded-lg border border-indigo-100 text-indigo-600">{sale.customer.id}</span>
        </div>
        <div className="flex justify-between items-center text-xs">
           <span className="text-slate-400 font-medium">Billed To:</span>
           <span className="font-bold">{sale.customer.name}</span>
        </div>
        <div className="flex justify-between items-center text-xs">
           <span className="text-slate-400 font-medium">Phone:</span>
           <span className="font-bold">{sale.customer.phone}</span>
        </div>
      </div>

      <div className="border-t border-b border-dashed border-slate-300 py-6 mb-8 flex justify-between text-[10px] uppercase font-black tracking-tighter">
        <div className="space-y-1">
          <p>Invoice: <span className="text-indigo-600">{sale.id}</span></p>
          <p>Date: {new Date(sale.timestamp).toLocaleDateString()}</p>
        </div>
        <div className="text-right space-y-1">
          <p>Time: {new Date(sale.timestamp).toLocaleTimeString()}</p>
          <p>Cashier: {sale.cashierId}</p>
        </div>
      </div>

      <div className="space-y-5 mb-10">
        {sale.items.map((item, idx) => (
          <div key={idx} className="flex justify-between items-start leading-tight">
            <div className="flex-1 pr-6">
              <p className="font-black text-slate-800 uppercase text-xs mb-1">{item.name}</p>
              <p className="text-[10px] text-slate-400 font-bold">{item.quantity} UNIT(S) @ ${item.price.toFixed(2)}</p>
            </div>
            <p className="font-black text-slate-900 text-sm">${item.total.toFixed(2)}</p>
          </div>
        ))}
      </div>

      <div className="border-t-2 border-slate-100 pt-8 space-y-3">
        <div className="flex justify-between text-xs font-bold text-slate-400 uppercase tracking-widest">
          <span>Net Total</span>
          <span>${sale.totalAmount.toFixed(2)}</span>
        </div>
        <div className="flex justify-between text-xs font-bold text-slate-400 uppercase tracking-widest">
          <span>SaaS Service Fee (0%)</span>
          <span>$0.00</span>
        </div>
        <div className="flex justify-between text-2xl font-black border-t-2 border-slate-950 pt-6 mt-4 tracking-tighter">
          <span>AMOUNT PAID</span>
          <span>${sale.totalAmount.toFixed(2)}</span>
        </div>
      </div>

      <div className="mt-16 text-center space-y-6">
        <div className="flex flex-col items-center">
           <div className="flex h-12 w-full max-w-[200px] border-x border-slate-300 items-end justify-center space-x-1.5 px-2">
             {[...Array(24)].map((_, i) => (
               <div key={i} className="bg-slate-900 w-px" style={{ height: `${20 + Math.random() * 80}%` }}></div>
             ))}
           </div>
           <p className="text-[8px] font-black tracking-[0.5em] text-slate-300 mt-2 uppercase">Verified Transaction</p>
        </div>
        <div className="pt-8 border-t border-slate-50">
          <p className="text-[10px] font-black uppercase text-indigo-500 tracking-[0.2em] mb-2">Thank You for Shopping</p>
          <p className="text-[9px] text-slate-400 font-bold leading-relaxed">Invoice generated by ShopMaster Cloud POS. Keep this for returns within 14 days under CID: {sale.customer.id}.</p>
        </div>
      </div>
    </div>
  );
};

export default Receipt;
